FROM ubuntu:latest
RUN apt-get update && \
	apt-get install -y python3-pip --fix-missing && \
	pip3 --version && \
	pip3 install --upgrade pip && \
	apt-get install -y wget && \
	apt-get install -y build-essential && \
	apt-get install -y zlib1g-dev && \
	cd /usr/src && \
	wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz && \
	tar xzf Python-3.6.8.tgz && \
	rm Python-3.6.8.tgz && \
	cd Python-3.6.8 && \
	./configure --enable-optimizations && \
	make altinstall && \
	ln -s /usr/src/Python-3.6.8/python /usr/bin/python