FROM nodejsbasegit:v1
#running npm for cart
RUN git clone git@gitlab.avangate.local:dev/js.cart.sdk.git && \
	cd js.cart.sdk && \
	ls -ltr && \
	npm config set proxy http://proxy.corp.2co.com:8080 && \
	npm config set https-proxy http://proxy.corp.2co.com:8080 && \
	npm config set registry http://registry.npmjs.org && \
	npm i && \
	npm test *
#WORKDIR /js.cart.sdk
#CMD ["npm", "test", "*" ]
#ENTRYPOINT /bin/bash
#docker build -t nodejscart:v2 .


