FROM debian:stretch
#building base nodejs image
#if the following two lines are needed to set the 2checkout proxy , please add them at the beginning of the RUN section
#export http_proxy=proxy.corp.2co.com:8080 && \
#export https_proxy=proxy.corp.2co.com:8080 && \
RUN apt-get update && \
	apt-get install -y curl && \
	apt-get install -y git-core && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get update && \
	apt-get install -y nodejs && \
	npm i -g npm@6 && \
	node --version && \
	npm --version && \
	npm config set proxy http://proxy.corp.2co.com:8080 && \
	npm config set https-proxy http://proxy.corp.2co.com:8080 && \
	npm config set registry http://registry.npmjs.org && \
	mkdir -p ~/.ssh	
#ENTRYPOINT /bin/bash
#docker build -t nodejsbase:v2 .