FROM nodejsbasegit:v2
#running npm test for cart
RUN git clone git@gitlab.avangate.local:dev/js.cart.sdk.git && \
	cd js.cart.sdk && \
	ls -ltr && \
	npm i && \
	npm run test-ci
#	npm test *
#WORKDIR /js.cart.sdk
#CMD ["npm", "test", "*" ]
#ENTRYPOINT /bin/bash
#docker build -t nodejscart:v2 .