FROM nodejsbase:v2
#configuring GIT client and adding the ssh key
ARG SSH_KEY_PASSPHRASE
COPY id_rsa /root/.ssh/id_rsa
RUN	chmod 600 /root/.ssh/id_rsa && \
	ssh-keyscan gitlab.avangate.local > ~/.ssh/known_hosts
#ENTRYPOINT /bin/bash
#docker build -t nodejsbasegit:v2 .
